name: ${project.name}
main: com.poixson.yumchain.YumChainPlugin
version: ${project.version}
api-version: ${spigot-short-version}
depend: [ pxnCommonBukkit ]
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
commands:
    yumchain:
        description: "I don't feel like eating this"
        usage: "Usage: /yumchain <cmd>"
permission-message: "You don't have permission to use this command."
permissions:
    yumchain.*:
        default: op
        description: Gives access to all yum chain commands
        children:
            yumchain.reset: true
    yumchain.reset:
        default: op
        description: Reset a players yum chain
